# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)
print(np.show_config())

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/anaconda\\Library\\include']
None


#### 3. Create a null vector of size 10

In [5]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [6]:
a=arr.size
b=arr.itemsize
print("memorysize={}".format(a*b))

memorysize=80


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [8]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [9]:
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [11]:
arr=np.arange(10,50,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### 8.  Reverse a vector (first element becomes last)

In [15]:
print(np.flipud(arr))

[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
arr=np.random.randint(0,9,(3,3))
print(arr)

[[4 2 6]
 [6 3 4]
 [0 6 6]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [21]:
arr=np.array([1,2,0,0,4,0])
arr=np.nonzero(arr)
print(arr)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [24]:
arr=np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [28]:
arr=np.random.random((3,3,3))
print(arr)

[[[0.40700535 0.80275894 0.27854847]
  [0.17561986 0.96389281 0.78305762]
  [0.97681044 0.91426397 0.40342891]]

 [[0.78561931 0.94459059 0.92920419]
  [0.95289431 0.94703417 0.08538117]
  [0.77680044 0.24537687 0.0944196 ]]

 [[0.82154034 0.7518241  0.47363065]
  [0.80264664 0.94961103 0.08425506]
  [0.64426579 0.83677723 0.18146037]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [30]:
arr=np.random.random((10,10))
print(arr)
print("min={}".format(np.min(arr)))
print("max={}".format(np.max(arr)))

[[0.91950681 0.45598898 0.1907249  0.47598185 0.4117342  0.74592139
  0.77760811 0.27205928 0.55513386 0.44837957]
 [0.99386214 0.81404047 0.88903662 0.20011179 0.47579617 0.74390485
  0.97064313 0.71093047 0.03173511 0.71523175]
 [0.8715003  0.17234718 0.72075399 0.25479963 0.7708148  0.73974693
  0.44325474 0.32846228 0.69307775 0.26873676]
 [0.95423872 0.27186795 0.626684   0.26711263 0.2811345  0.66126749
  0.06041187 0.75880009 0.41108792 0.58704496]
 [0.04378579 0.29420115 0.33984941 0.38471025 0.89093827 0.058066
  0.75501306 0.8198091  0.01117708 0.17463359]
 [0.86129751 0.89626556 0.42728254 0.62369779 0.52399258 0.22996305
  0.83142173 0.76470654 0.45321391 0.04756626]
 [0.27236762 0.15855969 0.27959972 0.09272465 0.84535798 0.16604012
  0.5196687  0.28396653 0.21947659 0.58911542]
 [0.34768724 0.6658468  0.67408503 0.74423671 0.99565491 0.80240701
  0.31970005 0.43997177 0.01295757 0.69541228]
 [0.03576703 0.11949364 0.88178536 0.35766584 0.77626661 0.21265843
  0.19279406 0

#### 14. Create a random vector of size 30 and find the mean value

In [34]:
arr=np.random.random(30)
print("mean={}".format(np.mean(arr)))

mean=0.5162414132609398


#### 15. Create a 2d array with 1 on the border and 0 inside

In [35]:
arr=np.ones((6,6))
arr[1:5,1:5]=0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [42]:
arr=np.ones((3,3))
np.pad(arr,pad_width = 2, mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [43]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [45]:
ans=np.diag([1,2,3,4],-1)
print(ans)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [46]:
ans=np.zeros((8,8))
ans[1::2,::2]=1
ans[::2,1::2]=1
print(ans)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [47]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)